version: '3.9'

services:
  n8n:
    # Tells Docker Compose to build an image from the Dockerfile in this directory
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-python:latest  # Tag the built image as 'n8n-python:latest'

    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_PORT: "5678"
      PORT: "5678"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_LISTEN_ADDRESS: "0.0.0.0"
      N8N_PROTOCOL: "https"
      N8N_HOST: "n8n.cedric-coding-projects.com"
      WEBHOOK_TUNNEL_URL: "https://n8n.cedric-coding-projects.com/"
      WEBHOOK_URL: "https://n8n.cedric-coding-projects.com/"
      N8N_SECURE_COOKIE: "true"
    volumes:
      - ~/.n8n:/root/.n8n
    tty: true 